language: php

sudo: false

php:
  - 7.0
  - hhvm

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.7.2/setup' -O - | php
  - echo "use=." > xp.ini
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - (EXCD=0; for i in `ls -1 src/test/config/unittest/*.ini | grep -v not-on-php-$TRAVIS_PHP_VERSION`; do echo "---> $i"; ./xp -cp test.xar xp.unittest.Runner $i; RES=$?; if [ $RES -ne 0 ]; then EXCD=$RES; fi; done; exit $EXCD;)
