# This provides an initial configuration to
# test xp-framework on http://travis-ci.org/

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.0.0/setup' -O - | php
  - echo "use=." > xp.ini
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - (EXCD=0; for i in src/test/config/unittest/*.ini; do echo "---> $i"; ./unittest $i; RES=$?; if [ $RES -ne 0 ]; then EXCD=$RES; fi; done; exit $EXCD;)

before_deploy:
  - export REL=`echo $TRAVIS_TAG | sed -e 's/^v//g'`
  - echo "===> Building release $REL"
  - sh .travis-build.sh $REL

deploy:
  provider: releases
  user: thekid
  password: "XY1YOzPCn0BF1AigB+V5ujRiuc3pGkPxR+EaAY1SpcQBTbiOmoGLSsO5TL7BDZ3aQnvfEQZo+vwHzye2MI069KP26PDWiX/3oCjkQ7l/ngIPys9WVJUgDdm79CQ01e9lrhd7nzlujABe0/BWO39FHVqBshO2nXainZz+OFGihqE"
  file: 
    - xp-rt-$REL.xar
    - glue.json
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    php: 5.4